apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-cancellation-worker-deployment
  labels:
    app: hotel-cancellation-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-cancellation-worker
  template:
    metadata:
      labels:
        app: hotel-cancellation-worker
    spec:
      containers:
      - name: hotel-cancellation-worker
        image: rdricardo/next-destiny:hotel-cancellation-worker

        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: awssm-secret
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: awssm-secret
              key: secret-access-key
        # resources:
        #   requests:
        #     memory: "64Mi"
        #     cpu: "100m"
        #   limits:
        #     memory: "128Mi"
        #     cpu: "200m"
      imagePullSecrets:
        - name: docker-secrets
