apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-api-prod
spec:
  acme:
    email: ricardo.dias@rdsolutions.digital
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-api-prod
    solvers:
    - http01:
        ingress:
          class: kong
