apiVersion: v1
kind: Service
metadata:
  name: orchestrator-api-service
spec:
  selector:
    app: orchestrator-api
  ports:
    - name: http      
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: https 
      protocol: TCP
      port: 443
      targetPort: 443
  type: ClusterIP