name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy-catalog:
    uses: ./.github/workflows/build-deploy.yml
    secrets: inherit
    with:
      dockerfille: src/Services/Catalog/Catalog.Api/Dockerfile
      tags: rdricardo/next-destiny:catalog-${{ github.sha }}
      deployment-name: catalog-api-deployment
  
  deploy-order:
    uses: ./.github/workflows/build-deploy.yml
    secrets: inherit
    with:
      dockerfille: src/Services/Order/Order.Api/Dockerfile
      tags: rdricardo/next-destiny:order-${{ github.sha }}
      deployment-name: order-api-deployment
